librosonline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vistaprevia/', include('vistaprevia.urls')),
    
]

vistaprevia/urls.py
from django.urls import path
from .views import index, contacto, cargar_imagen
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
        path('', index, name='index'),
        path('contacto/', contacto, name='contacto'),
        path('cargar/', cargar_imagen, name='cargar'),
]

vistaprevia/models.py
from django.db import models
from django.utils.html import format_html

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    def __str__(self):
        return '%s' % self.nombre 


class Producto(models.Model):
    Borrador = 'Borrador'
    Publicado = 'Publicado'
    Retirado = 'Retirado'
    APROBACION_PRODUCTO = (
        (Borrador, 'Borrador'),
        (Publicado, 'Publicado'),
        (Retirado, 'Retirado'),
    )
    producto = models.CharField(max_length=200)
    fecha_publicacion = models.DateTimeField("Fecha de Publicación")
    ruta_imagen = models.FileField(upload_to='fotos/%Y/%m/%d', default='defecto/defecto.png', blank=True, null=True)
    estado = models.CharField(max_length=10, choices=APROBACION_PRODUCTO, default='Borrador')
    categoria = models.ManyToManyField(Categoria)

    def tipo_de_producto(self):
        if self.estado == 'Retirado':
            return format_html('<span style="color: #f00;">{}</span>', self.estado,)
        if self.estado == 'Borrador':
            return format_html('<span style="color: #f0f;">{}</span>', self.estado,)
        if self.estado == 'Publicado':
            return format_html('<span style="color: #099;">{}</span>', self.estado,)
    
    def __str__(self):
        return ('<%s => %s: %s, %s>' % (self.__class__.__name__, self.producto, self.fecha_publicacion, self.ruta_imagen))

vistaprevia/forms.py
from django.forms import ModelForm
from .models import Producto

class CargaForm(ModelForm):
    class Meta:
        model = Producto
        fields = ('categoria', 'producto', 'fecha_publicacion', 'ruta_imagen')

        error_messages = {
            'producto' : {
                'required' : ('Se debe agregar un nombre de producto')
            },
            'fecha_publicacion' : {
                'required': ('Se debe agregar la fecha de publicación en el formato adecuado')
            },
        }
    def __init__(self, *args, **kwargs):
        super(CargaForm, self).__init__(*args, **kwargs)

vistaprevia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from .models import Producto
from .forms import CargaForm


#def index(request):
#   return HttpResponse("Hola Mundo!")

def contacto(request):
    return render(request, 'vistaprevia/contacto.html')

def index(request):
    contenido = {'nombre_sitio' : 'LibrosOnline' }
    para_minorista = {'tipo_usuario' : 'minorista', 'incremento' : '25'}
    para_mayorista = {'tipo_usuario' : 'mayorista', 'incremento' : '10'}
    return render(request, 'vistaprevia/index.html', {'contenido' : contenido,
                                                    'para_minorista' : para_minorista,
                                                    'para_mayorista' : para_mayorista})

def cargar_imagen(request):
    if request.method == 'POST':
        form = CargaForm(request.POST, request.FILES)

        if form.is_valid():
            producto = form.cleaned_data['producto']
            fecha_publicacion = form.cleaned_data['fecha_publicacion']
            ruta_imagen = form.cleaned_data['ruta_imagen']

            newdoc = Producto(producto = producto, fecha_publicacion = fecha_publicacion, ruta_imagen=ruta_imagen)
            newdoc.save()
            return redirect('index')
    else:
        form = CargaForm()
    return render(request, 'vistaprevia/formulario.html', {'form':form})

templates/vistaprevia/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
<link rel="stylesheet" type="text/css" href="{% static "vistaprevia/css/style.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "vistaprevia/css/bootstrap.css" %}" />
<meta  http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% block title %}
    {% if page_title %}
        {{ page_title }} -
    {% endif %}
        {{ site_name }}
{% endblock title %}
    </title>
    <meta name="keywords" content="{{ palabras_claves }}" />
    <meta name="description" content="{{ descripcion }}" />
    <script type="text/javascript" src="{% static 'vistaprevia/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'vistaprevia/js/bootstrap.js' %}"></script>
    <link href="{% static 'vistaprevia/css/jquery-ui.css' %}" rel="stylesheet" />
</head>
<body>
{% block contenedor %}

{% endblock contenedor %}

{% block scripts %}

{% endblock scripts %}

</body>
</html>

templates/vistaprevia/contacto.html
{% extends "vistaprevia/plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Pagina de contacto</h1>
        </div>
    </div>

    <main class="container-fluid">
        <div id="formulario_contacto" class="row">
            <div class="col-12">
                <h2>Contacto</h2>
                    <hr/>
                <form id="contact" action="" method="post" class="col-12 text-center">
                    <div class="col-xs-12">
                        <label id="label_nombre_completo" for="id_nombre_completo" class="col-2 text-left">Nombre y Apellido</label>
                        <input type="text" nombre="nombre" id="id_nombre_completo" />
                    </div>
                    <div class="col-xs-12">
                        <label id="label_email" for="id_email" class="col-2 text-left">EMAIL</label>
                        <input type="text" name="mail" id="id_email"  />
                    </div>
                    <div class="col-xs-12">
                        <label id="label_fecha" for="id_fecha" class="col-2 text-left">Fecha Limite de Entrega</label>
                        <input id="id_fecha" type="text" name="fecha" />
                    </div>
                    <div class="col-xs-12">
                        <label id="label_mensaje" for="id_mensaje" class="col-2 text-left">Consulta</label>
                        <textarea id="id_mensaje" name="consulta"></textarea>
                    </div>
                    <button type="submit" class="col-3 btn btn-primary bt-form">Enviar</button>
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'vistaprevia/js/jquery-ui.js' %}"></script>
    <script>
        $("#id_fecha").datepicker({
            inline: true
        });
    </script>
{% endblock scripts %}

templates/vistaprevia/formulario.html
{% extends "vistaprevia/plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}

    <div class="container">
        <div class="jumbotron">
            <h1>Página de Contacto</h1>
        </div>
    </div>

    <main class="container-fluid">
        <div id="formulario_contacto" class="row">
            <div class="col-12">
                <h2>Contacto</h2>
            <hr/>
                <form class="col-12 text-center" action="{% url 'cargar' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.categoria.errors }} {{ form.categoria.label_tag }}
                    <select name="categoria" required="" id="id_categoria">
                        <option value="1">Ciencia</option>
                        <option value="2">Tecnologia</option>
                        <option value="3">Lengua</option>
                    </select> 
                        {{ form.producto.errors }} {{ form.producto.label_tag}} {{ form.producto }}
                        {{ form.fecha_publicacion.errors }} {{ form.fecha_publicacion.label_tag}} {{ form.fecha_publicacion}}
                        {{ form.ruta_imagen.errors }} {{ form.ruta_imagen.label_tag }} {{ form.ruta_imagen }}
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
    </main>
    {% endblock %}
    
    {% block scripts %}
    <script src="{% static 'vistaprevia/js/jquery-ui.js' %}"></script>
    <script>
        $("#id_fecha_publicacion").datepicker({
            inline: true
        });
    </script>
    {% endblock scripts %}

templates/vistaprevia/index.html
{% extends "vistaprevia/plantilla.html" %}
{% block content %}
<div class="container">
<div class="jumbotron">
<h2>Bienvenido a: {{ contenido.nombre_sitio }} </h2>
</div>
</div>

<main class="container">
<div class="row">
    <section class="col-12" style="background-color: #25b98a; color : #fff;">
{% if para_minorista.incremento == '10' %}
    <h2>El incremento para minorista es del {{ para_minorista.incremento }}%!</h2>
{% elif para_minorista.incremento == '20' %}
    <h2>El incremento para minorista es del {{ para_minorista.incremento }}%!</h2>
{% else %}
    <h2>El incremento para minorista es del {{ para_minorista.incremento }}%!</h2>
{% endif %}
</section>
</div>
</main>
{% endblock content %}

{% block scripts %}
<script type="text/javascript">
    $('a').click(function(){
        alert("Estas por ir a otra pagina");
    });
</script>
{% endblock scripts %}

templates/vistaprevia/plantilla.html
{% extends "vistaprevia/base.html" %}
{% block contenedor %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">UTN MEDRANO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Desplegable
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Section 1</a>
          <a class="dropdown-item" href="#">Section 2</a>
          <a class="dropdown-item" href="#">Section 3</a>
        </div>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
      </li>
    </ul>
  </div>
</nav>

    {% block content %}{% endblock %}
    {% endblock %}